//
// Created by Sherman Yan on 1/17/23.
//

#ifndef COOKIEJAR_COOKIEFLAVORENUMS_H
#define COOKIEJAR_COOKIEFLAVORENUMS_H

enum CookieFlavor{
    CHOCOLATE_CHIP,
    OATMEAL_RAISIN,
    PEANUT_BUTTER,
    SUGAR_COOKIE,
    LAST_FLAVOR
};
#endif //COOKIEJAR_COOKIEFLAVORENUMS_H
